
import { SongProduct } from './types';

export const SONG_PRODUCTS: SongProduct[] = [
  {
    id: '1',
    title: 'Düğün Yemini Şarkısı',
    description: 'Kutsal yeminlerinizi sonsuza dek sürecek zamansız bir balada dönüştürün.',
    price: 4900,
    rating: 5,
    reviews: 124,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQCNQ07Cf5WGYPZwVfMvF0nLIYZxBl7ijOrtQLM3UPqyvc-8c-3qA-CXmWmpLu4O-82dxn56j5n-opj2Dhp9uSWDz_lKI7LrzzGTncFj4LXdXvVbsWgbd_X-u9FWOtjzj9mQ3SbjF_xJXHV2-gcT-Nop_yejpyHn3FZgPyAzUiUJXTy4HE4JW-uZU_c3TM9b-GBG_y8fT9KiQUzOO-5TnjMU1nhiduP8nniIPsXSYD-lDeY1TGQ9W_tXcNZcv9GiWypvh2zaCOrCc',
    category: 'Düğün ve Yıldönümü',
    isBestseller: true,
  },
  {
    id: '2',
    title: 'Doğum Günü Sürprizi',
    description: 'Büyük günleri için özelleştirilmiş eğlenceli, hareketli bir marş. Mükemmel bir sürpriz hediye.',
    price: 2900,
    rating: 4.5,
    reviews: 89,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC_Qz64_E_ztAj5_WEonCXKxh8Q85uMAQDNMEXL905GC3rjGgfuhGsLfQkyP2zkgXSnbmSmxio5Thm0kgr2vCo0dmvHnxAYz_fL5R8YmHi75cikWryzIOwZnTzhO3j_wh0JrHMrtLQUtgEfcNCtKf2bB8-VUuDYSp3NULt_4E__aoUh9JVKoxR9_aZRSA-pcglbp5E4uBY-4fjw7924uy1-scuPLWLi3qlnDCPda62LF-QPOUb41jun-EJ1QMcWQlrfYXDUVKu57lM',
    category: 'Doğum Günü ve Kutlama',
  },
  {
    id: '3',
    title: 'Özel Aşk Hikayesi',
    description: '"Biz"in hikayesini anlatın. İlk randevudan sonsuza uzanan bir yolculuk.',
    price: 3900,
    rating: 5,
    reviews: 42,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCR5GLSpeslYv_jPLWLM0gR7rAyd2m8-sOHozH_bQbDD7m91VJ369MB9NN00XODgcwvZ6Ug6aiIArSR5U5sjvdy-TSBn-cd8MGcZ4uIBohc4NfklNH6K8gQGm5wmmvxRcuQmpq7X6jCViMrTxiq0KapL_IbttHLf4vbxAMZb1wBHCu01LXVcVUU_fxMyOcVPFiRO9IXBUuJiBxbcVx74ov5ycyQ2GplhPgfaGWKJGI1qZP4vmTc0d1iAfCC7zkA9zozd3YiWa_AfO0',
    category: 'Düğün ve Yıldönümü',
    isNew: true,
  },
  {
    id: '4',
    title: 'Kurumsal Marka Cıngılı',
    description: 'Akılda kalan sonik markalaşma. Özel bir sesle şirket kimliğinizi yükseltin.',
    price: 9900,
    rating: 4,
    reviews: 15,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoThT4VoaMEBrVf2KPgcVOEDuZXx9oWPNa7w5Hnq8Zm5dbiV1s1pPRAuPHjUulZpmgCCglIfDY0VXEQrtEHPdfcs-2LyDI5g0oqVugHNlNiw2JU_zHaUFapiBhNjWthBrdRmiY3dUCVGYch_2ATC1hgipyPXwNVl5xDNxWzTZi5lBCQDGfnVAkdb8bvMc3nLzJAkrnRk7Kv07-KcaJB6Wsk2dfVirFEGsFmDAvqmjKAhlU1DDGSwlGM8FXjEW17QOTjlglpwa43Lc',
    category: 'Kurumsal ve Marka',
  },
  {
    id: '5',
    title: 'Altın Yıldönümü',
    description: 'Onlarca yıllık aşkı nostaljik, orkestral bir düzenleme ile kutlayın.',
    price: 5900,
    rating: 5,
    reviews: 56,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuABUUDm6hz8qBKlR0s9s7f_3tj148Vq7phFW5eMt8HhEmGywrI4XYP8JhzPXJE05MNnza9hj888tYpfzTNcYjh1pnIAidyxv3TxW-9duNkpokcVMZmgRxSPIACq71nF6Dtp6FgRkTRp6HNcIb2obtn7HDNc81Ne45dQh9HLVQPe4lMgt7I-wN_--v-gA-ruzbDIJVCO7hYznI7xNZ9i05ipKi3CvAA9mYNlYFKXO4zv65sktqT90HSy3SO8rhcbdstMSgA4WKIcIYM',
    category: 'Düğün ve Yıldönümü',
  },
  {
    id: '6',
    title: 'İçimden Geldi',
    description: 'Küçük anlar önemlidir. Geçici bir duyguyu veya içeriden bir şakayı şarkıya dökün.',
    price: 1900,
    rating: 4.5,
    reviews: 203,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjZCFxWNOPNi6T7dw6GXYF3zTe056_SbeZIJtGVMenrtezFNiKHFE1LJrTwymqQWC13OtSEK23nyR1FY9zIg-E7z_BajMoczomNaGJbJGIOF1XxCC9sGphLga3aaMOT8k_OcdFh1VSXvRATxlpbq2YFKKOzMrrrxnJpX7bJlZpb6aHi69kOjnIA_2V4p39i2E0RdsXLYYiNgRz-CqjwoQIKf5R7zQysFLMBvu20HBEW4-E7UalWyMx_8o8cbReRxIGZ-V5X4D-mDQ',
    category: 'İçimden Geldi',
  },
];
